---
- name: Obtener la dirección IP de las máquinas virtuales desde VMware usando la API REST
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_host: "mtyvcapac01.vmware.liverpool.com.mx"
    vcenter_username: "automation@vmware.liverpool.com.mx"
    vcenter_password: "An5¡bl3_au70m4t¡0n"
    validate_certs: no

  tasks:
    - name: Autenticarse en vCenter y obtener un token de sesión
      uri:
        url: "https://{{ vcenter_host }}/rest/com/vmware/cis/session"
        method: POST
        user: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        force_basic_auth: yes
        validate_certs: "{{ validate_certs }}"
        headers:
          Content-Type: "application/json"
      register: login_response

    - name: Verificar autenticación
      debug:
        msg: "Token de sesión obtenido: {{ login_response.json.value }}"

    - name: Obtener la lista de máquinas virtuales
      uri:
        url: "https://{{ vcenter_host }}/rest/vcenter/vm"
        method: GET
        headers:
          vmware-api-session-id: "{{ login_response.json.value }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_list_response

    - name: Mostrar la lista de máquinas virtuales
      debug:
        var: vm_list_response.json

    - name: Obtener la dirección IP de cada máquina virtual
      uri:
        url: "https://{{ vcenter_host }}/rest/vcenter/vm/{{ item.vm }}/guest/networking"
        method: GET
        headers:
          vmware-api-session-id: "{{ login_response.json.value }}"
        validate_certs: "{{ validate_certs }}"
      loop: "{{ vm_list_response.json }}"
      register: vm_ip_response

    - name: Mostrar la dirección IP de cada máquina virtual
      debug:
        msg: "VM {{ item.vm }} tiene la IP: {{ item.json.value[0].ip_addresses[0] }}"
      loop: "{{ vm_ip_response.results }}"
      when: item.json.value is defined and item.json.value | length > 0
