---
- name: Obtener información de máquinas virtuales de VMware
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_host: 'mtyvcapac01.vmware.liverpool.com.mx'
    vcenter_user: 'ansible@vmware.liverpool.com.mx'
    vcenter_password: 'L!v3rp00l'
    validate_certs: False  # Cambia a True si usas certificados válidos

  tasks:
    - name: Conectar a vCenter y obtener información de las VMs
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Mostrar información de las VMs
      debug:
        var: vm_info.virtual_machines