- name: T1 - Generar directorio para evidencias de preparchado
  ansible.builtin.file:
    path: "{{ ruta_base }}/prepatch"
    state: directory
    recurse: true
  register: result_directory_prepatch
 
- name: T1 - Generar directorio para evidencias de preparchado
  ansible.builtin.file:
    path: "{{ ruta_log_pre_patch }}"
    state: touch
   
- name: T2 - Ejecutar comandos
  ansible.builtin.include_tasks:
    file: print_results.yml
  vars:
    command_output_file: "{{ ruta_log_pre_patch }}"
    command_title: "{{ item.title }}"
    exec_command: "{{ item.command }}"
  loop: "{{ patching_commands }}"
 
- name: T3 - Validacion de servicios
  ansible.builtin.service_facts:
  register: result_service_status_pre

- name: T4 - Crear diccionario de estado de servicios
  ansible.builtin.set_fact:
    estado_servicios_prepatch: "{{ estado_servicios_prepatch | default([]) + [{'name': item['key'], 'status': item['value'].state}] }}" 
  loop: "{{ result_service_status_pre.ansible_facts.services | dict2items }}"
 
- debug:
    var:   estado_servicios_prepatch
 
- name: T5 - Imprimir resultados
  ansible.builtin.shell: |
    cat "{{ ruta_log_pre_patch }}"
  register: result_print_prepatch
  changed_when: false
  no_log: true
 
- name: Mensaje
  ansible.builtin.debug:
    var: result_print_prepatch.stdout_lines

