- name: Tomar snapshot de VM 
  vars:
    vcenter_hostname: "mtyvcapac01.vmware.liverpool.com.mx"
    vcenter_username: "automation@vmware.liverpool.com.mx"
    vcenter_password: "An5¡bl3_au70m4t¡0n"
    vm_name: "mtyplantso7"
    validate_certs: false

  tasks:
    - name: Verificar si se debe tomar el snapshot
      debug:
        msg: "Se va a tomar un snapshot para la VM {{ vm_name }}"
      when: make_snapshot == "Si"

    - name: Crear snapshot de la máquina virtual en VMware (si es requerido)
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter | default('Datacenter') }}"
        folder: "{{ folder | default('/') }}"
        name: "{{ vm_name }}"
        state: present
        snapshot_name: "Snapshot_Automatico_{{ ansible_date_time.date }}"
        description: "Snapshot creado por AAP"
        memory: false
        quiesce: false
      delegate_to: localhost
      when: make_snapshot == "Si"

    - name: Mensaje cuando no se toma snapshot
      debug:
        msg: "No se tomó snapshot, ya que el usuario seleccionó 'No'."
      when: make_snapshot == "No"