---
# tasks file for sendmail

- name: "Enviar notificacion - Ejecucion exitosa"
  when: notification_type == "Success"
  connection: local
  delegate_to: localhost
  become: true
  become_method: sudo
  become_user: root
  failed_when: false
  community.general.mail:
    host: "{{ SMTP_SERVER }}"
    port: "{{ SMTP_PORT }}"
    username: "{{ email_username | default(omit) }}"
    password: "{{ email_passwd | default(omit) }}"
    from: "{{ MAIL_FROM | default(mail_from)  }}"
    to: "{{ mail_to | default('ansible@liverpool.com.mx') }}"
    subject: "{{ email_subject }}"
    subtype: html
    secure: try
    body: |
      <html>
      <body>
      <p>Resumen de ejecución del <strong>Job ID {{ tower_job_id }}</strong> </p>
      <p style="color:green;"><strong>Ejecucion exitosa</strong><br><br></p>
      <p style="color:green;">
        {{ email_message | default('Ejecucion exitosa') }}
      </p>
      </body>
      </html>
    attach: 
      - "{{ attachment | default(omit) }}"
  

- name: "Enviar notificacion - Ejecucion fallida"
  when: notification_type == "Error"
  connection: local
  delegate_to: localhost
  become: true
  become_method: sudo
  become_user: root
  failed_when: false
  community.general.mail:
    host: "{{ SMTP_SERVER }}"
    port: "{{ SMTP_PORT }}"
    username: "{{ email_username | default(omit) }}"
    password: "{{ email_passwd | default(omit) }}"
    from: "{{ MAIL_FROM | default(mail_from)  }}"
    to: "{{ mail_to | default('xxx@liverpool.com.mx') }}"
    subject: "{{ email_subject }}"
    subtype: html
    secure: try
    body: |
      <html>
      <body>
      <p>Resumen de ejecución del <strong>Job ID {{ tower_job_id }}</strong> </p>
      <p style="color:red;"><strong>Ejecucion Fallida</strong><br><br></p>
      <p style="color:red;">
      {{ email_message |  default('Ejecucion fallida') }}
      </p>
      </body>
      </html>
    attach: 
      - "{{ attachment | default(omit) }}"