# tasks/main.yml

- name: Verificar si el envío de notificaciones está habilitado
  debug:
    msg: "El envío de notificaciones está deshabilitado."
  when: not enable_email_notification

- name: Enviar notificación por correo
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_user }}"
    password: "{{ smtp_password }}"
    to: "{{ email_to }}"
    from: "{{ email_from }}"
    subject: "{{ email_subject }}"
    body: "{{ email_body }}"
  when: enable_email_notification
